---
    # common playbook
  - hosts:         all
    become:        yes
    become_method: sudo
    gather_facts:  yes
    vars_files:
       - "../vars/common.yml"
    roles:
      - {role: mysql-install}
      #- {role: mysql-exporter}


      