---
apply_patches_db: false
# dbh: 
#   home: db193-si-ee


db_homes_config:

  db2103-gi-ee: &db2103-gi-ee
    home: db2103-gi-ee
    version: 21.3.0.0
    oracle_home: /u01/app/oracle/product/21/db1
    edition: EE
    opatch_minversion: 12.2.0.1.24

  # Current Mapping of ORACLE_HOMEs
  # use this mapping for fast change between the Release Updates
  # <<: * => merge values from alias and overwrite oracle_home + home
  db21-gi-ee:
    <<: *db2103-gi-ee
    oracle_home: /u01/app/oracle/product/21/db1
    home: db21-gi-ee

db_homes_installed:
  - home: db21-gi-ee
    apply_patches: true
    state: present
