- name: Download the exporter installer
  win_get_url:
    url: https://github.com/prometheus-community/windows_exporter/releases/download/v{{ win_node_exporter_version }}/windows_exporter-{{ win_node_exporter_version }}-amd64.msi
    dest: C:\ansible_examples\windows_exporter-{{ win_node_exporter_version }}-amd64.msi

- name: Install MSI
  win_package:
    path: C:\ansible_examples\windows_exporter-{{ win_node_exporter_version }}-amd64.msi
    state: present
